### ISSUE TITLE
what is ths goxc-0.1.13 tool?

### ISSUE THREAD

**Issue by Malvin999** [openyard/ebics#1]
hi, i'm learning this project uploaded by you, but I can not understand about the 'Generate structs with goxc-0.1.13' in your comment.
so, where can I obtain the 'goxc' executor?

**Comment by Kuriosr** [comment]
@tomask-de  please help~

**Comment by Malvin999** [comment]
I got the tool from the author's space ^_^

**Comment by tomask-de** [comment]
Glad you found it. 👍
